#!/usr/bin/env bash
# lint-agent-paths.sh — Verify agent definition files are in sync with the
# actual directory structure. Two checks:
#   1. Forward: paths referenced in agent files still exist (catches renames/deletions)
#   2. Reverse: source directories exist in at least one agent's structure map
#              (catches additions that weren't documented)
#
# Usage: ./scripts/lint-agent-paths.sh [--ci]
#   --ci  Exit non-zero on any warning (for CI gating)

set -euo pipefail

CI_MODE=0
if [[ "${1:-}" == "--ci" ]]; then
  CI_MODE=1
fi

REPO_ROOT="$(git rev-parse --show-toplevel)"
AGENT_DIR="${REPO_ROOT}/.claude/agents"
WARNINGS=0

# Directories to check for reverse coverage (source code roots)
SOURCE_ROOTS=(
  "src"
  "crates"
  "server/src"
  "server/tests"
  "scripts"
  ".claude/skills"
  ".claude/agents"
)

# Directories intentionally excluded from the structure map
# (build artifacts, generated output, non-source directories)
EXCLUDED_DIRS=(
  "src/wasm"          # WASM build output (generated by wasm-pack)
  "src/vite-env.d.ts" # not a directory
  ".claude/agents"    # meta — agents don't need to document themselves
)

if [[ ! -d "$AGENT_DIR" ]]; then
  echo "No agent definitions at ${AGENT_DIR}"
  exit 0
fi

# ── Check 1: Forward (referenced paths must exist) ──────────────────────

echo "=== Forward check: agent paths → filesystem ==="

for agent_file in "$AGENT_DIR"/*.md; do
  [[ -f "$agent_file" ]] || continue
  agent_basename=$(basename "$agent_file")

  # Extract backtick-quoted paths that end with /  (directory references)
  paths=$(grep -oP '`[^`]+/`' "$agent_file" 2>/dev/null | tr -d '`' | sort -u || true)

  for dir in $paths; do
    # Skip paths that are clearly example/template patterns
    [[ "$dir" == *"{{"* ]] && continue
    [[ "$dir" == *"<"* ]] && continue

    # Resolve relative to repo root
    full_path="${REPO_ROOT}/${dir}"
    if [[ ! -d "$full_path" ]]; then
      echo "WARN: ${agent_basename}: \`${dir}\` does not exist"
      WARNINGS=$((WARNINGS + 1))
    fi
  done
done

# ── Check 2: Reverse (source dirs must appear in agent maps) ────────────

echo "=== Reverse check: filesystem → agent maps ==="

# Collect all backtick-quoted paths from all agent files into one list.
# Include both directory paths (ending in /) and file paths (containing /)
# so that references like `src/types/index.ts` count as coverage for src/types/.
all_agent_paths=""
for agent_file in "$AGENT_DIR"/*.md; do
  [[ -f "$agent_file" ]] || continue
  extracted=$(grep -oP '`[^`]+/[^`]*`' "$agent_file" 2>/dev/null | tr -d '`' || true)
  all_agent_paths="${all_agent_paths}${extracted}"$'\n'
done

is_excluded() {
  local dir="$1"
  for excl in "${EXCLUDED_DIRS[@]}"; do
    [[ "$dir" == "$excl" || "$dir" == "$excl/" ]] && return 0
  done
  return 1
}

is_covered() {
  local dir="$1"
  # A directory is "covered" if:
  #   1. It is directly listed in an agent map (exact match), OR
  #   2. A parent directory is listed (parent covers children), OR
  #   3. Any child path under it is listed (e.g., src/components/gantt/
  #      means src/components/ is covered)

  # Check 3: any agent path starts with this dir (children are documented)
  if echo "$all_agent_paths" | grep -q "^${dir}/"; then
    return 0
  fi

  # Check 1 & 2: exact match or parent match (walk up the tree)
  local check="$dir"
  while true; do
    if echo "$all_agent_paths" | grep -qxF "${check}/"; then
      return 0
    fi
    if echo "$all_agent_paths" | grep -qxF "${check}"; then
      return 0
    fi
    parent=$(dirname "$check")
    [[ "$parent" == "$check" || "$parent" == "." ]] && break
    check="$parent"
  done
  return 1
}

for root in "${SOURCE_ROOTS[@]}"; do
  root_full="${REPO_ROOT}/${root}"
  [[ -d "$root_full" ]] || continue

  # Find immediate subdirectories (depth 1) under each source root
  # For top-level roots like "scripts/", check the root itself
  if [[ "$root" == "scripts" || "$root" == ".claude/skills" || "$root" == ".claude/agents" || "$root" == "server/src" || "$root" == "server/tests" ]]; then
    dirs_to_check="$root"
  else
    dirs_to_check=$(find "$root_full" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | sed "s|${REPO_ROOT}/||" | sort || true)
  fi

  for dir in $dirs_to_check; do
    [[ -z "$dir" ]] && continue
    is_excluded "$dir" && continue

    if ! is_covered "$dir"; then
      echo "WARN: \`${dir}/\` exists but is not documented in any agent structure map"
      WARNINGS=$((WARNINGS + 1))
    fi
  done
done

# ── Summary ─────────────────────────────────────────────────────────────

echo ""
if [[ $WARNINGS -gt 0 ]]; then
  echo "${WARNINGS} issue(s) found in agent structure maps."
  echo "Update the project structure maps in .claude/agents/*.md"
  if [[ $CI_MODE -eq 1 ]]; then
    exit 1
  fi
else
  echo "All agent directory references are valid and complete."
fi

exit 0
